# Generated by Django 3.1.1 on 2020-09-30 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apipostdoc',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='apiuserdoc',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
