# Generated by Django 3.1.1 on 2020-09-30 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20200930_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='apipostdoc',
            name='serial',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='apiuserdoc',
            name='serial',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
