# Generated by Django 3.1.1 on 2020-09-30 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20200930_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='apipostdoc',
            name='menu',
            field=models.CharField(default='hello', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='apiuserdoc',
            name='menu',
            field=models.CharField(default='hello', max_length=20),
            preserve_default=False,
        ),
    ]
